"""create mvp database foundation

Revision ID: 2ba7aadc5602
Revises: 
Create Date: 2026-04-30 00:51:10.649328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba7aadc5602'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('institutions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_institutions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_institutions_tenant_code')
    )
    op.create_index(op.f('ix_institutions_tenant_id'), 'institutions', ['tenant_id'], unique=False)
    op.create_table('experiment_packages',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('package_type', sa.Enum('standard', 'institution_custom', 'co_built', name='package_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_experiment_packages_institution_id_institutions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_experiment_packages_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_packages')),
    sa.UniqueConstraint('tenant_id', 'institution_id', 'slug', name='uq_packages_scope_slug')
    )
    op.create_index(op.f('ix_experiment_packages_institution_id'), 'experiment_packages', ['institution_id'], unique=False)
    op.create_index(op.f('ix_experiment_packages_slug'), 'experiment_packages', ['slug'], unique=False)
    op.create_index(op.f('ix_experiment_packages_tenant_id'), 'experiment_packages', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher', 'student', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_users_institution_id_institutions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('experiment_package_versions',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='package_status', native_enum=False), nullable=False),
    sa.Column('content_manifest_json', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_experiment_package_versions_institution_id_institutions')),
    sa.ForeignKeyConstraint(['package_id'], ['experiment_packages.id'], name=op.f('fk_experiment_package_versions_package_id_experiment_packages')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_experiment_package_versions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_package_versions')),
    sa.UniqueConstraint('package_id', 'version', name='uq_package_versions_package_version')
    )
    op.create_index(op.f('ix_experiment_package_versions_institution_id'), 'experiment_package_versions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_experiment_package_versions_package_id'), 'experiment_package_versions', ['package_id'], unique=False)
    op.create_index(op.f('ix_experiment_package_versions_tenant_id'), 'experiment_package_versions', ['tenant_id'], unique=False)
    op.create_table('courses',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('package_version_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='course_status', native_enum=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_courses_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_courses_institution_id_institutions')),
    sa.ForeignKeyConstraint(['package_version_id'], ['experiment_package_versions.id'], name=op.f('fk_courses_package_version_id_experiment_package_versions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_courses_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('institution_id', 'code', name='uq_courses_institution_code')
    )
    op.create_index(op.f('ix_courses_created_by_user_id'), 'courses', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_courses_institution_id'), 'courses', ['institution_id'], unique=False)
    op.create_index(op.f('ix_courses_package_version_id'), 'courses', ['package_version_id'], unique=False)
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('experiment_sessions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('student_user_id', sa.Uuid(), nullable=False),
    sa.Column('package_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'archived', name='session_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_experiment_sessions_course_id_courses')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_experiment_sessions_institution_id_institutions')),
    sa.ForeignKeyConstraint(['package_version_id'], ['experiment_package_versions.id'], name=op.f('fk_experiment_sessions_package_version_id_experiment_package_versions')),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], name=op.f('fk_experiment_sessions_student_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_experiment_sessions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_sessions')),
    sa.UniqueConstraint('course_id', 'student_user_id', name='uq_sessions_course_student')
    )
    op.create_index(op.f('ix_experiment_sessions_course_id'), 'experiment_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_experiment_sessions_institution_id'), 'experiment_sessions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_experiment_sessions_package_version_id'), 'experiment_sessions', ['package_version_id'], unique=False)
    op.create_index(op.f('ix_experiment_sessions_student_user_id'), 'experiment_sessions', ['student_user_id'], unique=False)
    op.create_index(op.f('ix_experiment_sessions_tenant_id'), 'experiment_sessions', ['tenant_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('package_version_id', sa.Uuid(), nullable=False),
    sa.Column('stage_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='rubric_status', native_enum=False), nullable=False),
    sa.Column('rubric_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_rubrics_course_id_courses')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_rubrics_institution_id_institutions')),
    sa.ForeignKeyConstraint(['package_version_id'], ['experiment_package_versions.id'], name=op.f('fk_rubrics_package_version_id_experiment_package_versions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_rubrics_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubrics')),
    sa.UniqueConstraint('package_version_id', 'course_id', 'stage_key', 'version', name='uq_rubrics_package_course_stage_version')
    )
    op.create_index(op.f('ix_rubrics_course_id'), 'rubrics', ['course_id'], unique=False)
    op.create_index(op.f('ix_rubrics_institution_id'), 'rubrics', ['institution_id'], unique=False)
    op.create_index(op.f('ix_rubrics_package_version_id'), 'rubrics', ['package_version_id'], unique=False)
    op.create_index(op.f('ix_rubrics_tenant_id'), 'rubrics', ['tenant_id'], unique=False)
    op.create_table('stage_records',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('stage_key', sa.String(length=50), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'not_started', 'in_learning', 'in_practice', 'submitted', 'revision_required', 'warning_confirmed', 'completed', 'skipped', name='stage_status', native_enum=False), nullable=False),
    sa.Column('skipped_learning', sa.Boolean(), nullable=False),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_stage_records_course_id_courses')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_stage_records_institution_id_institutions')),
    sa.ForeignKeyConstraint(['session_id'], ['experiment_sessions.id'], name=op.f('fk_stage_records_session_id_experiment_sessions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stage_records_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_records')),
    sa.UniqueConstraint('session_id', 'stage_key', name='uq_stage_records_session_stage')
    )
    op.create_index(op.f('ix_stage_records_course_id'), 'stage_records', ['course_id'], unique=False)
    op.create_index(op.f('ix_stage_records_institution_id'), 'stage_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_stage_records_session_id'), 'stage_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_stage_records_tenant_id'), 'stage_records', ['tenant_id'], unique=False)
    op.create_table('ai_call_logs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('stage_record_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('usage_type', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', name='ai_call_status', native_enum=False), nullable=False),
    sa.Column('request_metadata_json', sa.JSON(), nullable=False),
    sa.Column('response_metadata_json', sa.JSON(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_ai_call_logs_course_id_courses')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_ai_call_logs_institution_id_institutions')),
    sa.ForeignKeyConstraint(['session_id'], ['experiment_sessions.id'], name=op.f('fk_ai_call_logs_session_id_experiment_sessions')),
    sa.ForeignKeyConstraint(['stage_record_id'], ['stage_records.id'], name=op.f('fk_ai_call_logs_stage_record_id_stage_records')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ai_call_logs_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_call_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_call_logs'))
    )
    op.create_index(op.f('ix_ai_call_logs_course_id'), 'ai_call_logs', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_institution_id'), 'ai_call_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_prompt_version_id'), 'ai_call_logs', ['prompt_version_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_session_id'), 'ai_call_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_stage_record_id'), 'ai_call_logs', ['stage_record_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_tenant_id'), 'ai_call_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_usage_type'), 'ai_call_logs', ['usage_type'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_user_id'), 'ai_call_logs', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('stage_record_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('file_record_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'reviewed', 'accepted', 'revision_required', name='artifact_status', native_enum=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_artifacts_course_id_courses')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_artifacts_institution_id_institutions')),
    sa.ForeignKeyConstraint(['session_id'], ['experiment_sessions.id'], name=op.f('fk_artifacts_session_id_experiment_sessions')),
    sa.ForeignKeyConstraint(['stage_record_id'], ['stage_records.id'], name=op.f('fk_artifacts_stage_record_id_stage_records')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_artifacts_submitted_by_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_artifacts_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_course_id'), 'artifacts', ['course_id'], unique=False)
    op.create_index(op.f('ix_artifacts_institution_id'), 'artifacts', ['institution_id'], unique=False)
    op.create_index(op.f('ix_artifacts_session_id'), 'artifacts', ['session_id'], unique=False)
    op.create_index(op.f('ix_artifacts_stage_record_id'), 'artifacts', ['stage_record_id'], unique=False)
    op.create_index(op.f('ix_artifacts_submitted_by_user_id'), 'artifacts', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False)
    op.create_table('yellow_flags',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('source_stage_record_id', sa.Uuid(), nullable=True),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('source_review_id', sa.Uuid(), nullable=True),
    sa.Column('cleared_by_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('source_stage_key', sa.String(length=50), nullable=False),
    sa.Column('impact_stage_key', sa.String(length=50), nullable=True),
    sa.Column('flag_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='yellow_flag_severity', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'carried_forward', 'cleared', 'waived_by_teacher', name='yellow_flag_status', native_enum=False), nullable=False),
    sa.Column('acknowledged_by_student', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cleared_by_artifact_id'], ['artifacts.id'], name=op.f('fk_yellow_flags_cleared_by_artifact_id_artifacts')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_yellow_flags_course_id_courses')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_yellow_flags_institution_id_institutions')),
    sa.ForeignKeyConstraint(['session_id'], ['experiment_sessions.id'], name=op.f('fk_yellow_flags_session_id_experiment_sessions')),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], name=op.f('fk_yellow_flags_source_artifact_id_artifacts')),
    sa.ForeignKeyConstraint(['source_stage_record_id'], ['stage_records.id'], name=op.f('fk_yellow_flags_source_stage_record_id_stage_records')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_yellow_flags_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yellow_flags'))
    )
    op.create_index(op.f('ix_yellow_flags_cleared_by_artifact_id'), 'yellow_flags', ['cleared_by_artifact_id'], unique=False)
    op.create_index(op.f('ix_yellow_flags_course_id'), 'yellow_flags', ['course_id'], unique=False)
    op.create_index(op.f('ix_yellow_flags_institution_id'), 'yellow_flags', ['institution_id'], unique=False)
    op.create_index(op.f('ix_yellow_flags_session_id'), 'yellow_flags', ['session_id'], unique=False)
    op.create_index(op.f('ix_yellow_flags_source_artifact_id'), 'yellow_flags', ['source_artifact_id'], unique=False)
    op.create_index(op.f('ix_yellow_flags_source_review_id'), 'yellow_flags', ['source_review_id'], unique=False)
    op.create_index(op.f('ix_yellow_flags_source_stage_record_id'), 'yellow_flags', ['source_stage_record_id'], unique=False)
    op.create_index(op.f('ix_yellow_flags_tenant_id'), 'yellow_flags', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yellow_flags_tenant_id'), table_name='yellow_flags')
    op.drop_index(op.f('ix_yellow_flags_source_stage_record_id'), table_name='yellow_flags')
    op.drop_index(op.f('ix_yellow_flags_source_review_id'), table_name='yellow_flags')
    op.drop_index(op.f('ix_yellow_flags_source_artifact_id'), table_name='yellow_flags')
    op.drop_index(op.f('ix_yellow_flags_session_id'), table_name='yellow_flags')
    op.drop_index(op.f('ix_yellow_flags_institution_id'), table_name='yellow_flags')
    op.drop_index(op.f('ix_yellow_flags_course_id'), table_name='yellow_flags')
    op.drop_index(op.f('ix_yellow_flags_cleared_by_artifact_id'), table_name='yellow_flags')
    op.drop_table('yellow_flags')
    op.drop_index(op.f('ix_artifacts_tenant_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_submitted_by_user_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_stage_record_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_session_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_institution_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_course_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_ai_call_logs_user_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_usage_type'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_tenant_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_stage_record_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_session_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_prompt_version_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_institution_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_course_id'), table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    op.drop_index(op.f('ix_stage_records_tenant_id'), table_name='stage_records')
    op.drop_index(op.f('ix_stage_records_session_id'), table_name='stage_records')
    op.drop_index(op.f('ix_stage_records_institution_id'), table_name='stage_records')
    op.drop_index(op.f('ix_stage_records_course_id'), table_name='stage_records')
    op.drop_table('stage_records')
    op.drop_index(op.f('ix_rubrics_tenant_id'), table_name='rubrics')
    op.drop_index(op.f('ix_rubrics_package_version_id'), table_name='rubrics')
    op.drop_index(op.f('ix_rubrics_institution_id'), table_name='rubrics')
    op.drop_index(op.f('ix_rubrics_course_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_experiment_sessions_tenant_id'), table_name='experiment_sessions')
    op.drop_index(op.f('ix_experiment_sessions_student_user_id'), table_name='experiment_sessions')
    op.drop_index(op.f('ix_experiment_sessions_package_version_id'), table_name='experiment_sessions')
    op.drop_index(op.f('ix_experiment_sessions_institution_id'), table_name='experiment_sessions')
    op.drop_index(op.f('ix_experiment_sessions_course_id'), table_name='experiment_sessions')
    op.drop_table('experiment_sessions')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_package_version_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_institution_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_by_user_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_experiment_package_versions_tenant_id'), table_name='experiment_package_versions')
    op.drop_index(op.f('ix_experiment_package_versions_package_id'), table_name='experiment_package_versions')
    op.drop_index(op.f('ix_experiment_package_versions_institution_id'), table_name='experiment_package_versions')
    op.drop_table('experiment_package_versions')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_experiment_packages_tenant_id'), table_name='experiment_packages')
    op.drop_index(op.f('ix_experiment_packages_slug'), table_name='experiment_packages')
    op.drop_index(op.f('ix_experiment_packages_institution_id'), table_name='experiment_packages')
    op.drop_table('experiment_packages')
    op.drop_index(op.f('ix_institutions_tenant_id'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
