"""add stage blueprints

Revision ID: 82e61f25d0bf
Revises: 9b1f22f3c8a4
Create Date: 2026-04-30 01:41:02.040495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e61f25d0bf'
down_revision: Union[str, Sequence[str], None] = '9b1f22f3c8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_blueprints',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('package_version_id', sa.Uuid(), nullable=False),
    sa.Column('stage_key', sa.String(length=50), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('blueprint_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_stage_blueprints_institution_id_institutions')),
    sa.ForeignKeyConstraint(['package_version_id'], ['experiment_package_versions.id'], name=op.f('fk_stage_blueprints_package_version_id_experiment_package_versions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stage_blueprints_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_blueprints')),
    sa.UniqueConstraint('package_version_id', 'stage_key', name='uq_stage_blueprints_package_version_stage'),
    sa.UniqueConstraint('package_version_id', 'stage_order', name='uq_stage_blueprints_package_version_order')
    )
    op.create_index(op.f('ix_stage_blueprints_institution_id'), 'stage_blueprints', ['institution_id'], unique=False)
    op.create_index(op.f('ix_stage_blueprints_package_version_id'), 'stage_blueprints', ['package_version_id'], unique=False)
    op.create_index(op.f('ix_stage_blueprints_tenant_id'), 'stage_blueprints', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_blueprints_tenant_id'), table_name='stage_blueprints')
    op.drop_index(op.f('ix_stage_blueprints_package_version_id'), table_name='stage_blueprints')
    op.drop_index(op.f('ix_stage_blueprints_institution_id'), table_name='stage_blueprints')
    op.drop_table('stage_blueprints')
    # ### end Alembic commands ###
